### PR TITLE
Feature/cgi basic implementation

### PR DESCRIPTION
**Pull request by MrFacundo**
First CGI implementation

Implemented features to test:

- Execute CGI based on certain file extension. Executes .cgi file.
- Works with POST, GET, DELETE methods
- Make the route able to accept uploaded files 
- use the full path as PATH_INFO
- server should work with one CGI

`
 curl -X POST -F 'file=@a.txt' http://localhost:4242/cgi/file_handler.cgi
 curl  GET  http://localhost:4242/cgi/file_handler.cgi
 curl  -X DELETE -F 'file=@a.txt' http://localhost:4242/cgi/file_handler.cgi
 curl  GET  http://localhost:4242/cgi/file_handler.cgi
`

still to implement:
-  configure where files should be saved 
- Output of the CGI. If no content_length is returned from the CGI, EOF will mark the end of the returned data.
- for chunked request, your server needs to unchunk ut, the CGI will expect EOF as end of the body??
- program should call the CGI with the file requested as first argument??
- The CGI should be run in the correct directory for relative path file access??

### CODE REVIEW

**Comment by MrFacundo** [comment]
implemented / to test

- Dynamic upload directory (configure where files should be saved requirement)

```
location /file_manager	
{
cgi_path	.py /usr/bin/python3;
upload_store	uploads;
}
```

- The CGI runs in its own directory. This is apparently a requirement
- CGI returns headers and server sets them. This is also a requirement, apparently

**Comment by fmouronh** [comment]
> for chunked request, your server needs to unchunk it, the CGI will expect EOF as end of the body??
That means when we're receiving a single file split in multiple requests, we know we've reached end of file when the EOF character is found (you can use the EOF macro, as the value is system defined)

> program should call the CGI with the file requested as first argument??
yes. The idea is to run the cgi with the script requested as its first argument

> The CGI should be run in the correct directory for relative path file access??
execve should be called after calling cwd to the requested path relative to the locations root directory
in this case, a request for a location with the settings

`
location / {
                root    /var/www/html;
                cgi_path        .cgi /usr/bin/python3;
                index   file_handler.cgi;
}
`
should translate to the path /var/www/html/file_handler.cgi. It should call python like this in bash:
`$ .usr/bin/python3 /var/www/html/file_handler.cgi [args]`


We still need to work on the env. Should I add functionalities to the parser for handling CGI? or maybe add a new class for parsing uris in cgi requests

**Comment by MrFacundo** [comment]
> location / { root    /var/www/html; cgi_path        .cgi /usr/bin/python3; index   file_handler.cgi; }
should translate to the path /var/www/html/file_handler.cgi. It should call python like this in bash:
$ .usr/bin/python3 /var/www/html/file_handler.cgi [args]

ok, any additional features can be added on other branches. This branch only features what was mentioned in the comments. If the features work, this branch will be ready for merge

> We still need to work on the env. Should I add functionalities to the parser for handling CGI? or maybe add a new class for parsing uris in cgi requests

Any additional features can be added on other branches, **as long as they are required by the evaluation sheet or subject.**

**Comment by fmouronh** [comment]
the missing features are required by the RFC, and therefore will have to be added.

Everything seems to be working fine.
Merging

**Comment by MrFacundo** [comment]
👍 thanks for the merge @fmouronh 

Regarding the RFC, it's the same as with any other thing.
RFC compliance is not required by the subject, therefore it must not be implemented.

**Pull request merged**
