### PR TITLE
implemented POST method and file upload functions

### PR DESCRIPTION
**Pull request by MrFacundo**

### CODE REVIEW

**Comment by dda-cunh** [comment]
What's the point of parseFileContent, and why do you think It has to be done on Request?

**Comment by MrFacundo** [comment]
One way of doing file uploads, which is a subject requirements is using the content-type  [multipart/form-data](https://www.rfc-editor.org/rfc/rfc2046.html#section-5.1), using curl -X POST -F "file=@tests/uploadfile.txt" http://localhost:5050 or an html form.

To do this the body needs to be parsed in a specific way. The idea is to check the content type and IF it's multipart/form-data, do the file parsing or raise a bad request tag.  This is the request parsing.

The response object would then only check the parsed or flagged request and do the file writing and respond to the client.

It works as it is now, it just needs some refactoring for better separation of concerns.  That can be done on this same branch or in a new one.

**Comment by dda-cunh** [comment]
The request class should only focus on getting the data from the client. I do some minor checks like content-length because I need to know if the length matches the body and then I set a flag to say that its bad,  but even that kinda shouldn't be happening on request class. I should just pass the read information into a response handler.

**Comment by dda-cunh** [comment]
Any validation should be done on the response. Unless we want to implement a bridge class

**Comment by MrFacundo** [comment]
What you're doing with the BAD_REQUEST flag is ok. Since you're parsing the request it makes sense that you raise bad requests flags on the same step.

The Request class should handle the parsing of the incoming data, as it's doing now. And the Response class should handle the HTTP responses. That would be good separation of concerns and good encapsulation. Unless we want to create a specific module for file uploading (that's what NGINX does) but that would be over complicating things for a simple project like ours.

In terms of code, the refactoring would be simple:

- in Request::parseBody, we need to check for POST request with a multipart/form-data content type
- and call Request::parseFileContent, that will assign values to a struct data member with str file name and str file content, or raise a BAD_REQUEST flag
- the Response class would then handle the response accordingly.

Anyways, the file upload and POST request handling are now (minimally) implemented and unless there's a issue, this branch can be already merged.

**Comment by dda-cunh** [comment]
I will merge, but we need to revisit this in group.

**Pull request merged**
